---
# handlers file for roles/kubelet
- name: Reload service in all cases
  command: systemctl daemon-reload
  listen: restart_kubelet

- name: restart service
  ansible.builtin.service:
    name: "{{ item }}"
    state: restarted
    enabled: true
  listen: restart_kubelet
  loop: "{{ kubelet['service_name'] }}"

