---
- name: Add inventory hosts to /etc/hosts
  become: yes
  ansible.builtin.blockinfile:
    path: /etc/hosts
    marker: "# {mark} ANSIBLE MANAGED INVENTORY HOSTS"
    block: |
      {% for host in groups['all'] %}
      {{ hostvars[host]['ansible_host'] | default(host) }} {{ host }}
      {% endfor %}
  tags: hosts
#- name: write templates using jinja2
#  ansible.builtin.template:
#    src: "{{ item.src }}"
#    dest: "{{ item.dst }}"
#  loop: "{{ common.templates }}"
#
